stages:
  generate:
    cmd: python .\src\generate.py data/raw/
    deps:
    - .\src\generate.py
    - freq_table.html
    params:
    - generate
    outs:
    - data/raw
  store_features:
    cmd: python ./src/store_features.py data/raw/raw.csv data/features/
    deps:
      - src/store_features.py
      - data/raw/raw.csv
    params:
      - store_features
    outs:
      - data/features
  train:
    cmd: python ./src/train.py data/features/ data/models/
    deps:
      - src/train.py
      - data/features/
    params:
      - train
      - generate.sample_freq
    outs:
      - data/models
