stages:
  generate:
    cmd: python .\src\generate.py data/raw/
    deps:
    - .\src\generate.py
    - freq_table.html
    params:
    - generate
    outs:
    - data/raw
  store_features:
    cmd: python ./src/store_features.py data/raw/raw.csv data/features/features.tfrecords
    deps:
      - src/store_features.py
      - data/raw/raw.csv
    params:
      - store_features
    outs:
      - data/features
